In [ ]:
# You are managing the electonics section of a store . You neend to track the sales of **3 products**: headphone,smartwatch and speakers over **4 days **(monday to thrusday)
# row 0: headphone
# row 1: smartwatch
# row 2: speaker

In [ ]:
# task 1.1 Create a 1D Numpay array called cost_price containing the price for the 3 items: [1500,3000,5000].
# task 1.2 create a 2d numpy array called daily_sales  represting the number of units sold.

In [2]:
import numpy as np

cost_price = np.array([1500, 3000, 5000])

daily_sales = np.array([
    [10, 15, 8, 12],
    [5, 7, 4, 6],
    [2, 3, 2, 4]
])
print(cost_price)
print(cost_price.shape)
print(cost_price.ndim)
print(daily_sales)
print(daily_sales.shape)
print(daily_sales.ndim)



[1500 3000 5000]
(3,)
1
[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]
(3, 4)
2


In [ ]:
# Task 2.1 (Grace Units): The manager decides to add *2 "bonus" units* to every product's daily sale for a holiday report. Add 2 to the entire daily sales array. Task 2.2 (Revenue): Calculate the total řevenue for each day.

# Multiply the cost price array by the daily sales matrix.

# Observe how NumPy handles the multiplication of a 1D and 2D array.

# Task 2.3 (Scaling): Use np.sqrt() on the sales data to find the square root of all sales values for a statistical curve.

In [ ]:
# task D1: gread allocaton apply a greading system based on the studnts average

# avg >= 85: Gread A (score: 10)
# avg >= 70: Gread B (score: 8)
# avg >= 50: Gread C (score: 6)
# Below 50: No gread (Score: 0)


In [2]:
import numpy as np

avg = np.array([85, 70, 50])

grade = np.where(avg >= 85, "Grade A",
         np.where(avg >= 70, "Grade B",
         np.where(avg >= 50, "Grade C",
                  "No Grade")))

score = np.where(avg >= 85, 10,
         np.where(avg >= 70, 8,
         np.where(avg >= 50, 6,
                  0)))

# print("Average:", avg)
# print("Grade:", grade)
# print("Score:", score)


In [4]:
# task E1: The "copy vs view" challenge

# create a backup of the marks array
# modify the original array(e.g set marks [0,0] =  0)
# check if the backup array changed or remainder orignal.

# why is it dangerous to use backup = marks instead of backup = marks.copy()?



import numpy as np

marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95]
])

print("Original marks:\n", marks)


Original marks:
 [[78 85 90]
 [45 60 55]
 [88 92 95]]
