In [1]:
# A university monitors electricity usage(in units) of 4 hostel over 7 days(mon-sun).


# Array name - electricity
# shape: (4,7)
# row: hostel(h1,h2,h3,h4)
# column: days(mon-sun)

In [2]:
# Task A1: create a numpy array electricity using np.random.randint

# value between 120 and 650
# shape(4,7)


# Task A2: print the following Attributes of the array

# shape,number of dimension, total number of elements,and data type

In [3]:

import numpy as np
electricity = np.random.randint(120,650,size=(4,7))

print("Shape:", electricity.shape)
print("Number of dimensions:", electricity.ndim)
print("Total number of elements:", electricity.size)
print("Data type:", electricity.dtype)


Shape: (4, 7)
Number of dimensions: 2
Total number of elements: 28
Data type: int32


In [4]:
# task B1: hostel wise metrics

# find the avg electricity usage per hostel, the max usage per hostel , and identify which hostel has the highest avg usage


import numpy as np

# hostel-wise average usage
avg_usage = np.mean(electricity, axis=1)

# hostel-wise maximum usage
max_usage = np.max(electricity, axis=1)

# hostel with highest average usage
highest_avg_hostel = np.argmax(avg_usage) + 1

print("Average usage per hostel:", avg_usage)
print("Maximum usage per hostel:", max_usage)
print("Hostel with highest average usage: h",highest_avg_hostel)


Average usage per hostel: [357.14285714 223.42857143 379.28571429 351.85714286]
Maximum usage per hostel: [558 372 639 645]
Hostel with highest average usage: h 3


In [5]:
# task B2: day-wise Metrics

# calculate the total electricity consumption per day and identify the day with the highest total campus consumption

import numpy as np

# total electricity consumption per day
daily_total = np.sum(electricity, axis=0)

# day with highest total consumption
highest_day_index = np.argmax(daily_total)

print("Total electricity consumption per day:", daily_total)
print("Day with highest total campus consumption:", highest_day_index)


Total electricity consumption per day: [1046 1693 1099 1201 1423 1301 1419]
Day with highest total campus consumption: 1


In [6]:
# policy rule 
# if electricity usage on my day is greater than 550 units ,a 20% surcharge is applied

# task C1: 
# value > 550 -> multiplied by 1.20
# all other values remain unchanged


import numpy as np

electricity_surcharge = np.where(
    electricity > 550,
    electricity * 1.20,
    electricity
)

print(electricity_surcharge)


[[206.  288.  188.  307.  669.6 408.  545. ]
 [218.  121.  140.  300.  284.  372.  129. ]
 [379.  766.8 146.  389.  344.  280.  478. ]
 [243.  774.  750.  205.  237.  241.  267. ]]


In [7]:
# Task D1: Thinking task

# compare each hostel's daily usage with its own weekly avg. create a boolean matrix where:

# TRue : above hostel avg_usage
# False : Below or equal to hostel avg

# requirement 
# requires broadcasting of a(4, )array across a (4,7) array

hostel_avg = np.mean(electricity, axis=1)
print(hostel_avg)

above_avg = electricity > hostel_avg[:, np.newaxis]
print(above_avg)




[357.14285714 223.42857143 379.28571429 351.85714286]
[[False False False False  True  True  True]
 [False False False  True  True  True False]
 [False  True False  True False False  True]
 [False  True  True False False False False]]


In [8]:
# task E1 :
# reshape the electricity data into a single row representing weekly usage(shape: 1*28).


# task E2:
#  reshape the same data into 2 rows and 14 columns. ensure no dat is lost or duplicated


import numpy as np

# Task E1: reshape to 1 × 28
weekly_usage = electricity.reshape(1, 28)

# Task E2: reshape to 2 × 14
reshaped_usage = electricity.reshape(2, 14)

print(weekly_usage)
print(weekly_usage.shape)

print(reshaped_usage)
print(reshaped_usage.shape)


[[206 288 188 307 558 408 545 218 121 140 300 284 372 129 379 639 146 389
  344 280 478 243 645 625 205 237 241 267]]
(1, 28)
[[206 288 188 307 558 408 545 218 121 140 300 284 372 129]
 [379 639 146 389 344 280 478 243 645 625 205 237 241 267]]
(2, 14)
